openapi: 3.0.1
info:
  title: B2B
  description: API Definition of B2B
  version: 1.0.0
servers:
- url: http://localhost:8290/daraja/b2b
paths:
  /:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
